name: Build Docker Image  # Workflow name

# Trigger events
on:   # specifies events that trigger the workflow
  push:  # Runs on push events
  workflow_dispatch:  # Manual trigger from GitHub UI
  release:
    types: [released]

jobs:
  build:  # Job name
    runs-on: ubuntu-latest  # Runner machine, Ubuntu VM

    steps:
      # Step 1: Checkout code
      - name: Checkout code 
        uses: actions/checkout@v2  # Use the GitHub Actions 'checkout' action, version 2

      # Step 2: Setup Buildx
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2  # Docker Buildx action

      # Step 3: Get branch name
      - name: Get branch name 
        run: |                 # run in shell command
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')  # Extract branch name
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV  # Save branch name

      # Step 4: Set Docker tag
      - name: Set Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG_NAME="${{ github.ref_name }}"  # Use the release tag name
          else
            TAG_NAME="${{ github.sha }}"  # Use git hash and branch name
          fi
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT  # Save the tag for later use

      # Step 5: Login to Docker Hub
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2  # Docker login action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub token

      # Step 6: Build and push image
      - name: Build and push Docker image  
        run: |
          TAG_NAME="${{ steps.docker_tag.outputs.tag }}"  # Use the output from the docker_tag step
          echo "Pushing image: $TAG_NAME"  # Log the tag name
          
          docker build -t ceararojas/sysrepo:$TAG_NAME .  # Build image with the new tag format
          docker push ceararojas/sysrepo:$TAG_NAME  # Push image with the new tag format