name: Build Docker Image

on:
  push:
    branches:
      - main     # Auto-build Docker image on main branch push
  workflow_dispatch:   # Manual trigger for other branches like development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name:latest .
        docker push your-dockerhub-username/your-image-name:latest
      env:
        DOCKER_BUILDKIT: 1
