name: Build Docker Image

on:
  push:
    branches:
      - main    
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select the branch to build the Docker image'
        required: true
        default: 'main'  # Default branch
        options:
          - main
          - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.target_branch }}  # Check out the selected branch

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get short Git commit hash
      id: vars
      run: |
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Display COMMIT_HASH
      run: |
        echo "Git hash: $COMMIT_HASH"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        echo "Building and pushing image with tag: $COMMIT_HASH"
        docker build -t ceararojas/sysrepo:$COMMIT_HASH .
        docker push ceararojas/sysrepo:$COMMIT_HASH
      env:
        DOCKER_BUILDKIT: 1
