name: Create Release Branch

on:
  release:
    types: [published]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create Release Branch
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          # Extract major version from the tag
          MAJOR_VERSION=$(echo "$TAG_NAME" | cut -d '.' -f 1)
          
          # Format the branch name as release_<major-version>
          BRANCH_NAME="release-${MAJOR_VERSION}" # Branch name will be like release_v1

          # Check if the branch already exists
          if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
              echo "Branch '$BRANCH_NAME' already exists. No new branch created."
          else
              # Check if the release is a major release (e.g., v1.0.0 -> v1)
              if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                  git checkout -b "$BRANCH_NAME"
                  git push origin "$BRANCH_NAME"
                  echo "Branch '$BRANCH_NAME' created and pushed."
              else
                  echo "Not a major release. No branch created."
              fi
          fi
