name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      system:
        description: 'Select test rack for deployment'
        required: true
        default: 'System A'
        type: choice
        options:
          - Klaus
          - Kalle
          - Kari
          - Klara
      services:
        description: |
          Select services to deploy (comma-separated list).
          Available options:
          - New MBMS
          - Legacy MBMS
          - REST API
          - Device Logger
          Example: "New MBMS,Legacy MBMS"
        required: true
        default: 'New MBMS'
        
jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Tags
        id: get-tags
        run: |
          tags=$(git tag -l --points-at HEAD)
          echo "::set-output name=tags::$(echo $tags | tr '\n' ',')"

  deploy:
    runs-on: ubuntu-latest
    needs: fetch-tags

    steps:
      - name: Print Available Tags
        run: |
          echo "Available tags: ${{ needs.fetch-tags.outputs.tags }}"
          echo "Selected System: ${{ github.event.inputs.system }}"
          echo "Selected Services: ${{ github.event.inputs.services }}"

      - name: Deploy Services
        run: |
          IFS=',' read -ra SERVICES <<< "${{ github.event.inputs.services }}"
          for service in "${SERVICES[@]}"; do
            echo "Deploying ${service} version ${{ github.event.inputs.version }} to ${{ github.event.inputs.system }}"
            # Add deployment commands for each service here
            if [[ "$service" == "New MBMS" ]]; then
              echo "Deploying New MBMS..."
              # Your deployment commands for New MBMS
            elif [[ "$service" == "Legacy MBMS" ]]; then
              echo "Deploying Legacy MBMS..."
              # Your deployment commands for Legacy MBMS
            elif [[ "$service" == "REST API" ]]; then
              echo "Deploying REST API..."
              # Your deployment commands for REST API
            elif [[ "$service" == "Device Logger" ]]; then
              echo "Deploying Device Logger..."
              # Your deployment commands for Device Logger
            fi
          done

      - name: Complete Deployment
        run: echo "Deployment completed successfully!"
