name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define repo name
        id: repo-name
        run: echo "REPO_NAME=ceararojas/sys-testing" >> $GITHUB_ENV

      - name: Extract Git commit hash
        id: commit-hash
        run: echo "GIT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Read current version
        id: version
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set Docker tags for images
        id: docker-tags
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          
          if [ "$BRANCH_NAME" = "main" ]; then
            # Main branch uses both version-commit and version tags
            VERSION="${CURRENT_VERSION}-${GIT_COMMIT_HASH}"
            TAGS="${REPO_NAME}:${VERSION} ${REPO_NAME}:${CURRENT_VERSION}"

          elif [ "$BRANCH_NAME" = "development" ]; then
            # Development branch uses commit-beta tag
            TAGS="${REPO_NAME}:${GIT_COMMIT_HASH}-beta"

          else
            # Other branches use just commit hash as tag
            TAGS="${REPO_NAME}:${GIT_COMMIT_HASH}"
            
          fi
          echo "DOCKER_TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
