name: Docker Build and Push

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define repo name
        run: echo "REPO_NAME=ceararojas/sysrepo" >> $GITHUB_ENV

      - name: Extract Git commit hash
        run: echo "GIT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          if [ "$BRANCH" = "main" ]; then
            TAG="${{ env.GIT_COMMIT_HASH }}-main"

          elif [ "$BRANCH" = "development" ]; then
            TAG="${{ env.GIT_COMMIT_HASH }}-dev"
          
          else
            TAG="commit-feature"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REPO_NAME }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.REPO_NAME }}:${{ env.TAG }}
