name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checks out your repository code to the runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Sets up Docker Buildx, a Docker CLI plugin for extended build capabilities

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Logs in to Docker Hub using credentials stored in GitHub Secrets

      - name: Extract Git commit hash
        id: vars
        run: echo "GIT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)-beta" >> $GITHUB_ENV
        # Extracts a short commit hash and sets it as an environment variable

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ceararojas/sys-testing:${{ env.GIT_COMMIT_HASH }}
        # Builds and pushes the Docker image to Docker Hub

