name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define repos name
        id: vars
        run: echo "REPO_NAME=ceararojas/sys-testing" >> $GITHUB_ENV

      - name: Extract Git commit hash, use first 8 codes.
        id: vars
        run: echo "GIT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Read current version
        id: version
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Setting up docker tags for images
        id: tags
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          
          if [ "$BRANCH_NAME" = "main" ]; then
            VERSION="${CURRENT_VERSION}-${GIT_COMMIT_HASH}"
            TAGS="${REPO_NAME}:${VERSION} ${REPO_NAME}:${CURRENT_VERSION}"

          elif [ "$BRANCH_NAME" = "development" ]; then
            TAGS="${REPO_NAME}:${GIT_COMMIT_HASH}-beta"

          else
            # For other branches, use just commit
            TAGS="${REPO_NAME}:${GIT_COMMIT_HASH}"
          
          fi
          echo "DOCKER_TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
