name: Deploy

on:
  workflow_dispatch:  # This allows manual triggering
    inputs:           # Optional inputs you can provide when triggering manually
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options: 
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "Deploying to production"
          # Add production deployment steps here
        elif [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          echo "Deploying to staging"
          # Add staging deployment steps here
        fi
